<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findAllOrdered()
	{
		//$dql = 'SELECT cat FROM AppBundle\Entity\Category cat ORDER BY cat.name DESC';
		//$query = $this->getEntityManager()->createQuery($dql);

		$qb = $this->createQueryBuilder('cat')
					->addOrderBy('cat.name','DESC');
		$this->addFortuneCookiesJoinAndSelect($qb);
		$query = $qb->getQuery();
		return $query->execute();
	}

	public function search($term)
	{
		$qb = $this->createQueryBuilder('cat')
					->andWhere('cat.name like :term 
						or cat.iconKey like :term
						or fc.fortune  like :term
					')
					->setParameter('term','%'.$term.'%');
		$this->addFortuneCookiesJoinAndSelect($qb);
		return 	$qb->getQuery()
					->execute();
	}
	public function findWithJoinFortuneCookies($id)
	{
		$qb = $this->createQueryBuilder('cat')
					->andWhere('cat.id = :id')
					->setParameter('id',$id);
		$this->addFortuneCookiesJoinAndSelect($qb);
		return 	$qb->getQuery()
					->getOneOrNullResult();
	}


	private function addFortuneCookiesJoinAndSelect(QueryBuilder $qb)
	{
		return $qb->leftJoin('cat.fortuneCookies','fc')
				->addSelect('fc');
	}
}
